steps:

  - id: "Executando docker-compose"
    name: 'docker/compose'
    args: [ '-f', 'docker-compose.cloudbuild.yaml', 'up', '-d' ]

  - id: "Permissão em www"
    name: 'docker'
    args: [ 'exec','-u','root','-t','app','chown','-R','www-data:www-data','/var/www' ]

  - id: "Executando composer"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'composer', 'install' ]

  - id: "Copiando .env"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'cp', '/var/www/.env.example', '/var/www/.env' ]

  - id: "Executando key:generate"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'php', '/var/www/artisan', 'key:generate' ]

  - id: "Executando migrations"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'php', '/var/www/artisan', 'migrate' ]

  - id: "Executando phpunit"
    name: 'docker'
    args: [ 'exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml' ]

  - id: "Building image from Dockerfile.prod"
    name: 'docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/app-laravel:$SHORT_SHA', '-f', 'Dockerfile.prod', '.' ]

  - id: "Pushing image"
    name: 'docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/app-laravel:$SHORT_SHA' ]

  - id: "Adjusting deployment file - k8s"
    name: 'gcloud'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        sed 's#img-app-depoyment#gcr.io/$PROJECT_ID/app-laravel:$SHORT_SHA#g' .k8s/app/deployment.yaml > k8s/app/deployment-new.yaml;
        cat k8s/app/deployment-new.yaml;
